### ISSUE TITLE
ASL_f4_loader fails to recognize RCT on USB3

### ISSUE THREAD

**Issue by stieg** [autosportlabs/ASL_F4_bootloader#11]
When I attempt to flash my firmware on RCT using USB3 I see the following stack trace from the loader:

``` python
[stieg@lucious firmware]$ asl_f4_loader -p /dev/ttyACM0 -f platform/rct/main.ihex 
Place your device into bootloader mode and then press any key
Updating firmware...
[                                                  ] 0%Traceback (most recent call last):
  File "/usr/bin/asl_f4_loader", line 9, in <module>
    load_entry_point('asl-f4-loader==0.1.0', 'console_scripts', 'asl_f4_loader')()
  File "build/bdist.linux-x86_64/egg/asl_f4_loader/fw_update.py", line 253, in main
  File "build/bdist.linux-x86_64/egg/asl_f4_loader/fw_update.py", line 174, in update_firmware
Exception: Error flashing device, no response!
```

and I see the following message in my dmesg output:

```
[87147.582242] usb 3-2: new full-speed USB device number 7 using xhci_hcd
[87147.747037] usb 3-2: New USB device found, idVendor=16d0, idProduct=07f1
[87147.747041] usb 3-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[87147.747042] usb 3-2: Product: RaceCapture Track
[87147.747044] usb 3-2: Manufacturer: Autosport Labs
[87147.747045] usb 3-2: SerialNumber: 205D31644333
[87147.747506] cdc_acm 3-2:1.0: ttyACM0: USB ACM device
[87195.896164] cdc_acm 3-2:1.0: failed to set dtr/rts
[87230.639454] cdc_acm 3-2:1.0: failed to set dtr/rts
[87233.323891] cdc_acm 3-2:1.0: failed to set dtr/rts
```

When I plug into USB2 I see the following in dmesg:

```
[87385.297364] usb 3-2: USB disconnect, device number 7
[87388.234798] usb 1-1.2: new full-speed USB device number 31 using ehci-pci
[87388.322727] usb 1-1.2: New USB device found, idVendor=16d0, idProduct=07f1
[87388.322734] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[87388.322738] usb 1-1.2: Product: RaceCapture Track
[87388.322741] usb 1-1.2: Manufacturer: Autosport Labs
[87388.322743] usb 1-1.2: SerialNumber: 205D31644333
[87388.323467] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
[87407.770127] usb 1-1.2: USB disconnect, device number 31
[87407.772400] cdc_acm 1-1.2:1.0: failed to set dtr/rts
[87407.951541] usb 1-1.2: new full-speed USB device number 32 using ehci-pci
[87408.039875] usb 1-1.2: New USB device found, idVendor=16d0, idProduct=07f1
[87408.039882] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[87408.039886] usb 1-1.2: Product: RCT Bootloader
[87408.039889] usb 1-1.2: Manufacturer: Autosport Labs
[87408.039891] usb 1-1.2: SerialNumber: 205D31644333
[87408.040722] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
```

and loader succeeds.

**Comment by stieg** [comment]
Kernel info:

```
$ uname -a
Linux lucious.stiegnet.us 4.5.6-300.fc24.x86_64 #1 SMP Wed Jun 1 21:29:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by stieg** [comment]
As of now this blocks RCT Kickstarter since we need to be able to support USB3 devices.

**Comment by Jeff-Ciesielski** [comment]
Fixed by https://github.com/autosportlabs/ASL_F4_bootloader/commit/14bfeeb59ddee42af3e6096e33e50ae5dfd71f85
