### ISSUE TITLE
Bootloader does not function correctly on Mac

### ISSUE THREAD

**Issue by stieg** [autosportlabs/ASL_F4_bootloader#2]
Receiving the following error consistently on OSX:

```
[stieg@Penguin firmware]$ sudo asl_f4_loader -f stm32_base/main.ihex
Place your device into bootloader mode and then press any key
Searching for an active bootloader
Unable to locate an active bootloader
Usage: asl_f4_loader [options]

Options:
  -h, --help            show this help message and exit
  -f INPUT_FILENAME, --filename=INPUT_FILENAME
                        Filename of .ihex file to process
  -p SER_PORT, --port=SER_PORT
                        (optional)path to serial port we're talking on ex:
                        /dev/ttyACM0
  -v VERBOSE, --verbose=VERBOSE
                        turn on verbose debugging
[stieg@Penguin firmware]$ sudo asl_f4_loader -f stm32_base/main.ihex
Place your device into bootloader mode and then press any key
Searching for an active bootloader
Found bootloader on: /dev/cu.usbmodem1421
Updating firmware...
[**************************************************] 100%

Verifying firmware
Traceback (most recent call last):
  File "/usr/local/bin/asl_f4_loader", line 9, in <module>
    load_entry_point('asl-f4-loader==0.0.6', 'console_scripts', 'asl_f4_loader')()
  File "build/bdist.macosx-10.10-intel/egg/asl_f4_loader/fw_update.py", line 246, in main
  File "build/bdist.macosx-10.10-intel/egg/asl_f4_loader/fw_update.py", line 199, in update_firmware
Exception: Error validating flash on device. Updgrade failed
```

**Comment by brentpicasso** [comment]
Much of the same library code is used when upgrading within app. Do you experience the same problem?

**Comment by stieg** [comment]
I can't upgrade on the app due to the internal trello task I filed about the app not being able to find RCP in bootloader mode.  Mine is borked after the failed upgrade attempt.

**Comment by stieg** [comment]
Unable to reproduce on version 0.3.1.  Closing..
